### ISSUE TITLE
URLs with special symbols are not supported

### ISSUE THREAD

**Issue by defder-su** [BGforgeNet/yawbdl#2]
Git Bash, Windows, NTFS

> $ ./yawbdl.py -d btdigg.org -o yawbdl_btdigg.org --no-fail --retries 10
(1/23062) 20110205030240 http://btdigg.org:80/  [Skip: already on disk]
(2/23062) 20110226231305 http://btdigg.org:80/about.html  [Skip: already on disk]
(3/23062) 20110226231319 http://btdigg.org:80/top100.html  [Skip: already on disk]
...
(37/23062) 20110812222012 http://btdigg.org/gray.css  [Skip: already on disk]
(38/23062) 20110812222153 http://btdigg.org/about.html  [OK]
(39/23062) 20110812222202 http://btdigg.org/plugins/browser_plugin.html  [Skip: already on disk]
(40/23062) 20110812222215 http://btdigg.org/favicon.ico      failed to download, retrying after 2 seconds...
    failed to download, retrying after 4 seconds...
    failed to download, retrying after 6 seconds...
[OK]
(41/23062) 20110812222221 http://btdigg.org/search?q=Pioneer%20One  Traceback (most recent call last):
  File "D:\SaveSites\yawbdl.py", line 160, in <module>
    download_files(snap_list)
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "D:\SaveSites\yawbdl.py", line 73, in download_files
    download_file(snap)
    ~~~~~~~~~~~~~^^^^^^
  File "D:\SaveSites\yawbdl.py", line 130, in download_file
    write_file(fpath, content)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\SaveSites\yawbdl.py", line 149, in write_file
    with open(fpath, "wb") as file:
         ~~~~^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'yawbdl_btdigg.org\\20110812222221\\search?q=Pioneer%20One'

I suppose that's because of `?` is not allowed for filenames.

Possible solution: replace `?` with `@` (as `wget` [does](https://www.gnu.org/software/wget/manual/wget.html#index-Windows-file-names)) on write.

**Comment by burner1024** [comment]
Sure, try windows branch.
I don't have Windows to test myself.

**Comment by defder-su** [comment]
Downloads without errors, but writes [OK] instead of [Skip: already on disk] when file exists.

**Comment by burner1024** [comment]
This should fix it, I think.

**Comment by defder-su** [comment]
It works. Many thanks.

**Comment by burner1024** [comment]
Cool.
There's probably more where this came from, but I don't want to dive into that until an actual need arises.

**Comment by defder-su** [comment]
> There's probably more where this came from, but I don't want to dive into that until an actual need arises.

Yes, `*` should be also replaced with `%2A`.

```
yawbdl.py -d demiart.ru -o yawbdl_demiart.ru --no-fail --retries 10 --delay 2
...
(3045/2055429) 20041117185903 http://demiart.ru/;j=true;s=1024*768;d=32;rand=0.928625017786173  Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\Programs\Git\usr\bin\yawbdl.py", line 229, in <module>
    download_files(snap_list)
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Git\usr\bin\yawbdl.py", line 121, in download_files
    download_file(snap)
    ~~~~~~~~~~~~~^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Git\usr\bin\yawbdl.py", line 192, in download_file
    write_file(fpath, content)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Git\usr\bin\yawbdl.py", line 217, in write_file
    with open(fpath, "wb") as file:
         ~~~~^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'yawbdl_demiart.ru\\20041117185903\\;j=true;s=1024*768;d=32;rand=0.928625017786173'
```

Ideally:
> Wget escapes the characters ‘\’, ‘|’, ‘/’, ‘:’, ‘?’, ‘"’, ‘*’, ‘<’, ‘>’, and the control characters in the ranges 0–31 and 128–159. In addition to this, Wget ... uses ‘@’ instead of ‘?’ to separate the query portion of the file name from the rest.

**Comment by burner1024** [comment]
Try escape branch

**Comment by defder-su** [comment]
> Downloads without errors, but writes [OK] instead of [Skip: already on disk] when file exists.

That reproduces again for URLs with special symbols.

**Comment by burner1024** [comment]
show log

**Comment by defder-su** [comment]
```
$ ./yawbdl.py -d demiart.ru -o yawbdl_demiart.ru --no-fail --retries 10 --delay 2
Getting snapshot list...
Got snapshot list!
(1/2055429) 20031015074815 http://demiart.ru:80/  [Skip: already on disk]
(2/2055429) 20031016111427 http://demiart.ru:80/about.shtml  [Skip: already on disk]
(3/2055429) 20031016112139 http://demiart.ru:80/base.shtml  [Skip: already on disk]
(4/2055429) 20031016112323 http://demiart.ru:80/banners.shtml  [Skip: already on disk]
(5/2055429) 20031016112701 http://demiart.ru:80/ash.css  [Skip: already on disk]
(6/2055429) 20031016113118 http://demiart.ru:80/eva.shtml  [Skip: already on disk]
(7/2055429) 20031016113309 http://demiart.ru:80/fallen_angel.shtml  [Skip: already on disk]
(8/2055429) 20031016113809 http://demiart.ru:80/evol.shtml  [Skip: already on disk]
(9/2055429) 20031016114729 http://demiart.ru:80/guestbook.shtml  [Skip: already on disk]
(10/2055429) 20031016114735 http://demiart.ru:80/checklinks.shtml  [Skip: already on disk]
(11/2055429) 20031016114812 http://demiart.ru:80/index_eng.shtml  [Skip: already on disk]
(12/2055429) 20031016115654 http://demiart.ru:80/links.shtml  [Skip: already on disk]
(13/2055429) 20031016120029 http://demiart.ru:80/natali.shtml  [Skip: already on disk]
(14/2055429) 20031016120442 http://demiart.ru:80/melancholy.shtml  [Skip: already on disk]
(15/2055429) 20031016120928 http://demiart.ru:80/inwindowind.shtml  [Skip: already on disk]
(16/2055429) 20031016121338 http://demiart.ru:80/newyear.shtml  [Skip: already on disk]
(17/2055429) 20031016234115 http://demiart.ru:80/visual_rightbot.gif  [Skip: already on disk]
(18/2055429) 20031017000056 http://demiart.ru:80/visual_righttop.gif  [Skip: already on disk]
(19/2055429) 20031017081730 http://demiart.ru:80/visual_top.gif  [Skip: already on disk]
(20/2055429) 20031017113543 http://demiart.ru:80/visuals/ash121_fallen_angel.jpg  [Skip: already on disk]
(21/2055429) 20031017124921 http://demiart.ru:80/visuals/ash125_natali.jpg  [Skip: already on disk]
(22/2055429) 20031017125806 http://demiart.ru:80/visuals/ash126_inwindowind.jpg  [Skip: already on disk]
(23/2055429) 20031017133754 http://demiart.ru:80/visuals/ash128_baselevel.jpg  [Skip: already on disk]
(24/2055429) 20031018155446 http://demiart.ru:80/portfolio_item.gif  [Skip: already on disk]
(25/2055429) 20031018160308 http://demiart.ru:80/preview/AnchSu.jpg  [Skip: already on disk]
(26/2055429) 20031018164415 http://demiart.ru:80/preview/bunx.gif  [Skip: already on disk]
(27/2055429) 20031018165037 http://demiart.ru:80/preview/cyborg.gif  [Skip: already on disk]
(28/2055429) 20031018171426 http://demiart.ru:80/preview/dolphin.gif  [Skip: already on disk]
(29/2055429) 20031018174049 http://demiart.ru:80/preview/emma.gif  [Skip: already on disk]
(30/2055429) 20031018180215 http://demiart.ru:80/preview/feelings.gif  [Skip: already on disk]
(31/2055429) 20031018214513 http://demiart.ru:80/preview/heresy_we.gif  [Skip: already on disk]
(32/2055429) 20031018215802 http://demiart.ru:80/preview/hertanel.gif  [Skip: already on disk]
(33/2055429) 20031018223838 http://demiart.ru:80/preview/medallion.gif  [Skip: already on disk]
(34/2055429) 20031018232727 http://demiart.ru:80/preview/seele.gif  [Skip: already on disk]
(35/2055429) 20031018233946 http://demiart.ru:80/preview/she.gif  [Skip: already on disk]
(36/2055429) 20031019011423 http://demiart.ru:80/preview/storm.gif  [Skip: already on disk]
(37/2055429) 20031019015356 http://demiart.ru:80/preview/without_you.gif  [Skip: already on disk]
(38/2055429) 20031019022056 http://demiart.ru:80/tutorials/tutorials.gif  [Skip: already on disk]
(39/2055429) 20031019022456 http://demiart.ru:80/visuals/ash124_newyear.jpg  [Skip: already on disk]
(40/2055429) 20031019025337 http://demiart.ru:80/visuals/ash127_eva.jpg  [Skip: already on disk]
(41/2055429) 20031019031252 http://demiart.ru:80/visuals/ash129_evol.jpg  [Skip: already on disk]
(42/2055429) 20031128024258 http://demiart.ru:80/  [Skip: already on disk]
(43/2055429) 20031207080913 http://demiart.ru:80/aniston.shtml  [Skip: already on disk]
(44/2055429) 20031207083101 http://demiart.ru:80/banners.shtml  [Skip: already on disk]
(45/2055429) 20031207084820 http://demiart.ru:80/base.shtml  [Skip: already on disk]
(46/2055429) 20031207090204 http://demiart.ru:80/checklinks.shtml  [Skip: already on disk]
(47/2055429) 20031207091612 http://demiart.ru:80/eva.shtml  [Skip: already on disk]
(48/2055429) 20031207091900 http://demiart.ru:80/evol.shtml  [Skip: already on disk]
(49/2055429) 20031207092707 http://demiart.ru:80/fallen_angel.shtml  [Skip: already on disk]
(50/2055429) 20031207092912 http://demiart.ru:80/guestbook.shtml  [Skip: already on disk]
(51/2055429) 20031207093705 http://demiart.ru:80/heresy.shtml  [Skip: already on disk]
(52/2055429) 20031207095032 http://demiart.ru:80/index.shtml  [Skip: already on disk]
(53/2055429) 20031207095720 http://demiart.ru:80/index_eng.shtml  [Skip: already on disk]
(54/2055429) 20031207101224 http://demiart.ru:80/jovovich.shtml  [Skip: already on disk]
(55/2055429) 20031207102658 http://demiart.ru:80/links.shtml  [Skip: already on disk]
(56/2055429) 20031207103742 http://demiart.ru:80/melancholy.shtml  [Skip: already on disk]
(57/2055429) 20031210081956 http://demiart.ru:80/banners.gif  [Skip: already on disk]
(58/2055429) 20031210085254 http://demiart.ru:80/banners/ash_ban3.gif  [Skip: already on disk]
(59/2055429) 20031210091116 http://demiart.ru:80/banners/ash_ban_100x100.gif  [Skip: already on disk]
(60/2055429) 20031210093512 http://demiart.ru:80/banners/ash_banner3.jpg  [Skip: already on disk]
(61/2055429) 20031210094600 http://demiart.ru:80/banners/ash_banner_468x60.gif  [Skip: already on disk]
(62/2055429) 20031210102251 http://demiart.ru:80/banners/ash_britney.jpg  [Skip: already on disk]
(63/2055429) 20031210105544 http://demiart.ru:80/banners/ash_britney2.gif  [Skip: already on disk]
(64/2055429) 20031210110427 http://demiart.ru:80/banners/best_new_soft.gif  [Skip: already on disk]
(65/2055429) 20031210120544 http://demiart.ru:80/banners/button_ash_4_gas13.gif  [Skip: already on disk]
(66/2055429) 20031210123014 http://demiart.ru:80/banners/button_ash_4_gas13_2.gif  [Skip: already on disk]
(67/2055429) 20031210123748 http://demiart.ru:80/banners/chart_banner2.gif  [Skip: already on disk]
(68/2055429) 20031210133405 http://demiart.ru:80/banners/dolphin.gif  [Skip: already on disk]
(69/2055429) 20031210135309 http://demiart.ru:80/banners/elvira.gif  [Skip: already on disk]
(70/2055429) 20031210142023 http://demiart.ru:80/banners/kin_dza_dza.gif  [Skip: already on disk]
(71/2055429) 20031210145512 http://demiart.ru:80/banners/mdb.gif  [Skip: already on disk]
(72/2055429) 20031210150917 http://demiart.ru:80/banners/ninth_gate.gif  [Skip: already on disk]
(73/2055429) 20031210160339 http://demiart.ru:80/banners/pos_ash2.gif  [Skip: already on disk]
(74/2055429) 20031210161557 http://demiart.ru:80/banners/rawbanner4.gif  [Skip: already on disk]
(75/2055429) 20031210164112 http://demiart.ru:80/banners/rawbanner5.gif  [Skip: already on disk]
(76/2055429) 20031210170621 http://demiart.ru:80/banners/run_lola_run.gif  [Skip: already on disk]
(77/2055429) 20031210172346 http://demiart.ru:80/banners/sage.gif  [Skip: already on disk]
(78/2055429) 20031210175134 http://demiart.ru:80/banners/sandra.gif  [Skip: already on disk]
(79/2055429) 20031225025011 http://demiart.ru:80/news.gif  [Skip: already on disk]
(80/2055429) 20031225031826 http://demiart.ru:80/pixel.gif  [Skip: already on disk]
(81/2055429) 20031225033333 http://demiart.ru:80/point.gif  [Skip: already on disk]
(82/2055429) 20031225035134 http://demiart.ru:80/preview/aniston.gif  [Skip: already on disk]
(83/2055429) 20031225040722 http://demiart.ru:80/preview/baselevel.gif  [Skip: already on disk]
(84/2055429) 20031225043146 http://demiart.ru:80/preview/chan.gif  [Skip: already on disk]
(85/2055429) 20031225045654 http://demiart.ru:80/preview/combining.gif  [Skip: already on disk]
(86/2055429) 20031225050559 http://demiart.ru:80/preview/combo2.gif  [Skip: already on disk]
(87/2055429) 20031225061326 http://demiart.ru:80/preview/eva.gif  [Skip: already on disk]
(88/2055429) 20031225063627 http://demiart.ru:80/preview/evol.gif  [Skip: already on disk]
(89/2055429) 20031225070822 http://demiart.ru:80/preview/inwindowind.gif  [Skip: already on disk]
(90/2055429) 20031225073451 http://demiart.ru:80/preview/irckovrov.gif  [Skip: already on disk]
(91/2055429) 20031225082348 http://demiart.ru:80/preview/jovovich.gif  [Skip: already on disk]
(92/2055429) 20031225092045 http://demiart.ru:80/preview/luw.gif  [Skip: already on disk]
(93/2055429) 20031225093303 http://demiart.ru:80/preview/melancholy.gif  [Skip: already on disk]
(94/2055429) 20031225094318 http://demiart.ru:80/  [Skip: already on disk]
(95/2055429) 20031225095138 http://demiart.ru:80/preview/natali.gif  [Skip: already on disk]
(96/2055429) 20031225103929 http://demiart.ru:80/preview/realfire.gif  [Skip: already on disk]
(97/2055429) 20031225105430 http://demiart.ru:80/preview/rustygear.gif  [Skip: already on disk]
(98/2055429) 20031225112019 http://demiart.ru:80/preview/veridea.gif  [Skip: already on disk]
(99/2055429) 20031225114357 http://demiart.ru:80/preview/why.gif  [Skip: already on disk]
(100/2055429) 20031225115347 http://demiart.ru:80/table_hr.gif  [Skip: already on disk]
(101/2055429) 20031225124912 http://demiart.ru:80/visual_bottom.gif  [Skip: already on disk]
(102/2055429) 20031225131416 http://demiart.ru:80/visual_bottomc.gif  [Skip: already on disk]
(103/2055429) 20031225132739 http://demiart.ru:80/visual_center.gif  [Skip: already on disk]
(104/2055429) 20031225134504 http://demiart.ru:80/visual_centertop.gif  [Skip: already on disk]
(105/2055429) 20031225140911 http://demiart.ru:80/visual_left.gif  [Skip: already on disk]
(106/2055429) 20040109132157 http://demiart.ru:80/newyear.shtml  [Skip: already on disk]
(107/2055429) 20040113103805 http://demiart.ru:80/old_news.shtml  [Skip: already on disk]
(108/2055429) 20040113104200 http://demiart.ru:80/portfolio.shtml  [Skip: already on disk]
(109/2055429) 20040116110344 http://demiart.ru:80/search_images.shtml  [Skip: already on disk]
(110/2055429) 20040116110544 http://demiart.ru:80/skins.shtml  [Skip: already on disk]
(111/2055429) 20040118053047 http://demiart.ru:80/spectrum_gfx.shtml  [Skip: already on disk]
(112/2055429) 20040118053525 http://demiart.ru:80/truecolor.shtml  [Skip: already on disk]
(113/2055429) 20040118053932 http://demiart.ru:80/tutorials/chan.shtml  [Skip: already on disk]
(114/2055429) 20040119193533 http://demiart.ru:80/tutorials/chrome.shtml  [Skip: already on disk]
(115/2055429) 20040119195214 http://demiart.ru:80/tutorials/combining.shtml  [Skip: already on disk]
(116/2055429) 20040119195843 http://demiart.ru:80/tutorials/combo2.shtml  [Skip: already on disk]
(117/2055429) 20040121134552 http://demiart.ru:80/tutorials/fx_1.shtml  [Skip: already on disk]
(118/2055429) 20040121141315 http://demiart.ru:80/tutorials/gear.shtml  [Skip: already on disk]
(119/2055429) 20040121210820 http://demiart.ru:80/tutorials/combining/16_3.gif  [Skip: already on disk]
(120/2055429) 20040123083510 http://demiart.ru:80/tutorials/gfx_1.shtml  [Skip: already on disk]
(121/2055429) 20040123085053 http://demiart.ru:80/tutorials/index.shtml  [Skip: already on disk]
(122/2055429) 20040123085805 http://demiart.ru:80/tutorials/liquid.shtml  [Skip: already on disk]
(123/2055429) 20040125030525 http://demiart.ru:80/tutorials/luw.shtml  [Skip: already on disk]
(124/2055429) 20040125031255 http://demiart.ru:80/tutorials/papyrus.shtml  [Skip: already on disk]
(125/2055429) 20040125032853 http://demiart.ru:80/tutorials/realfire.shtml  [Skip: already on disk]
(126/2055429) 20040126113715 http://demiart.ru:80/visible.js  [Skip: already on disk]
(127/2055429) 20040126130028 http://demiart.ru:80/veridea.shtml  [Skip: already on disk]
(128/2055429) 20040127224938 http://demiart.ru:80/webdesign_com.shtml  [Skip: already on disk]
(129/2055429) 20040127225938 http://demiart.ru:80/why.shtml  [Skip: already on disk]
(130/2055429) 20040127233545 http://demiart.ru:80/visual.shtml  [Skip: already on disk]
(131/2055429) 20040129060355 http://demiart.ru:80/z80.shtml  [Skip: already on disk]
(132/2055429) 20040131001050 http://demiart.ru:80/download/download_dreamweaver_mx.shtml  [Skip: already on disk]
(133/2055429) 20040203011512 http://demiart.ru:80/forum/  [Skip: already on disk]
(134/2055429) 20040203012533 http://demiart.ru:80/guestbook.shtml  [Skip: already on disk]
(135/2055429) 20040203013022 http://demiart.ru:80/heresy.shtml  [Skip: already on disk]
(136/2055429) 20040203014059 http://demiart.ru:80/index.shtml  [Skip: already on disk]
(137/2055429) 20040203014635 http://demiart.ru:80/links.shtml  [Skip: already on disk]
(138/2055429) 20040203015840 http://demiart.ru:80/portfolio.shtml  [Skip: already on disk]
(139/2055429) 20040203020936 http://demiart.ru:80/skins.shtml  [Skip: already on disk]
(140/2055429) 20040203023510 http://demiart.ru:80/truecolor.shtml  [Skip: already on disk]
(141/2055429) 20040203023739 http://demiart.ru:80/tutorials/index.shtml  [Skip: already on disk]
(142/2055429) 20040203025258 http://demiart.ru:80/visual.shtml  [Skip: already on disk]
(143/2055429) 20040203164619 http://demiart.ru:80/karlo.jpg  [Skip: already on disk]
(144/2055429) 20040208192527 http://www.demiart.ru:80/  [Skip: already on disk]
(145/2055429) 20040214235210 http://demiart.ru:80/about.shtml  [Skip: already on disk]
(146/2055429) 20040215000439 http://demiart.ru:80/banners.shtml  [Skip: already on disk]
(147/2055429) 20040215000915 http://demiart.ru:80/checklinks.shtml  [Skip: already on disk]
(148/2055429) 20040215213504 http://demiart.ru:80/books/12923m.jpg  [Skip: already on disk]
(149/2055429) 20040215214341 http://demiart.ru:80/books/81341m.jpg  [Skip: already on disk]
(150/2055429) 20040222091135 http://demiart.ru:80/z80.shtml  [Skip: already on disk]
(151/2055429) 20040222101910 http://demiart.ru:80/forum/index.php?act=Help  [OK]
(152/2055429) 20040222102707 http://demiart.ru:80/forum/index.php?act=Login&amp  [OK]
(153/2055429) 20040222104000 http://demiart.ru:80/forum/index.php?act=Members&amp  [OK]
(154/2055429) 20040222105046 http://demiart.ru:80/forum/index.php?act=Reg&amp  [OK]
(155/2055429) 20040222105430 http://demiart.ru:80/forum/index.php?act=Search&amp  [OK]
(156/2055429) 20040222105609 http://demiart.ru:80/download/index.shtml  [Skip: already on disk]
(157/2055429) 20040222110235 http://demiart.ru:80/forum/index.php  [Skip: already on disk]
(158/2055429) 20040226054919 http://demiart.ru:80/  [Skip: already on disk]
(159/2055429) 20040228080952 http://demiart.ru:80/forum/index.php?c=3  [OK]
(160/2055429) 20040228081328 http://demiart.ru:80/forum/index.php?showforum=4  [OK]
(161/2055429) 20040228081427 http://demiart.ru:80/forum/index.php?act=Stats  [OK]
(162/2055429) 20040228081501 http://demiart.ru:80/forum/index.php?showforum=5  [OK]
(163/2055429) 20040228081544 http://demiart.ru:80/forum/index.php?c=5  [OK]
(164/2055429) 20040228081859 http://demiart.ru:80/forum/index.php?showforum=6  [OK]
(165/2055429) 20040228081939 http://demiart.ru:80/forum/index.php?act=calendar  [OK]
(166/2055429) 20040228081955 http://demiart.ru:80/forum/index.php?s=&act=chat&pop=1  [OK]
(167/2055429) 20040228082110 http://demiart.ru:80/forum/index.php?showforum=10  [OK]
(168/2055429) 20040228082113 http://demiart.ru:80/forum/index.php?act=idx  [OK]
(169/2055429) 20040228082123 http://demiart.ru:80/forum/index.php?showforum=7  [OK]
(170/2055429) 20040228145014 http://demiart.ru:80/forum/style_images/1/f_norm_no.gif  [Skip: already on disk]
(171/2055429) 20040228152823 http://demiart.ru:80/forum/style_images/1/f_poll.gif  [Skip: already on disk]
(172/2055429) 20040228155134 http://demiart.ru:80/forum/style_images/1/f_poll_no.gif  [Skip: already on disk]
(173/2055429) 20040228191947 http://demiart.ru:80/forum/style_images/1/icon1.gif  [Skip: already on disk]
(174/2055429) 20040229125101 http://demiart.ru:80/forum/style_images/1/cal_newevent.gif  [Skip: already on disk]
(175/2055429) 20040229131835 http://demiart.ru:80/forum/style_images/1/icon12.gif  [Skip: already on disk]
(176/2055429) 20040305085552 http://demiart.ru:80/forum/index.php?showtopic=133&amp  [OK]
(177/2055429) 20040305085728 http://demiart.ru:80/forum/index.php?showuser=27  [OK]
(178/2055429) 20040305085741 http://demiart.ru:80/forum/index.php?showtopic=128&amp  [OK]
(179/2055429) 20040305085830 http://demiart.ru:80/forum/index.php?showforum=9      failed to download, retrying after 4 seconds...
    failed to download, retrying after 8 seconds...
    failed to download, retrying after 12 seconds...
    failed to download, retrying after 16 seconds...
    failed to download, retrying after 20 seconds...
    failed to download, retrying after 24 seconds...
    failed to download, retrying after 28 seconds...
    failed to download, retrying after 32 seconds...
    failed to download, retrying after 36 seconds...
[OK]
(180/2055429) 20040305085905 http://demiart.ru:80/forum/index.php?showtopic=90&amp  [OK]
(181/2055429) 20040305085921 http://demiart.ru:80/forum/index.php?showuser=1  [OK]
(182/2055429) 20040305085950 http://demiart.ru:80/forum/index.php?showtopic=129&amp  [OK]
(183/2055429) 20040305090222 http://demiart.ru:80/forum/index.php?showuser=24  [OK]
(184/2055429) 20040305090327 http://demiart.ru:80/forum/index.php?showtopic=89&amp  [OK]
(185/2055429) 20040305090333 http://demiart.ru:80/forum/index.php?showtopic=131&amp  [OK]
(186/2055429) 20040305090334 http://demiart.ru:80/forum/index.php?showuser=57  [OK]
(187/2055429) 20040305090338 http://demiart.ru:80/forum/index.php?showforum=8  [OK]
(188/2055429) 20040305090349 http://demiart.ru:80/forum/index.php?showtopic=121&amp  [OK]
(189/2055429) 20040309120046 http://demiart.ru:80/links_humor.shtml  [Skip: already on disk]
(190/2055429) 20040309120100 http://demiart.ru:80/links_films.shtml  [Skip: already on disk]
(191/2055429) 20040309120104 http://demiart.ru:80/pos/index.htm  [Skip: already on disk]
(192/2055429) 20040309120107 http://demiart.ru:80/portfolio/drr/index.htm  [Skip: already on disk]
(193/2055429) 20040309120143 http://demiart.ru:80/links_dark.shtml  [Skip: already on disk]
(194/2055429) 20040309120219 http://demiart.ru:80/links_music.shtml  [Skip: already on disk]
(195/2055429) 20040309120358 http://demiart.ru:80/links_gfx.shtml  [Skip: already on disk]
(196/2055429) 20040309120403 http://demiart.ru:80/forum/index.php?showuser=78  [OK]
(197/2055429) 20040309120405 http://demiart.ru:80/portfolio2.shtml  [Skip: already on disk]
(198/2055429) 20040309120409 http://demiart.ru:80/guestbook.shtml?n=50  [OK]
(199/2055429) 20040309120419 http://demiart.ru:80/links_zxscene.shtml  [Skip: already on disk]
(200/2055429) 20040309120423 http://demiart.ru:80/links_others.shtml  [Skip: already on disk]
```

**Comment by defder-su** [comment]
I understood: `escaped_url = escaped_url.replace("?", "@")` doesn't affect now, because of `?` replaces with `%3F` earlier, so filenames are different now from previously downloaded.

**Comment by defder-su** [comment]
Indeed, when restarted:
```
$ ./yawbdl.py -d demiart.ru -o yawbdl_demiart.ru --no-fail --retries 10 --delay 2
Getting snapshot list...
    failed to get snapshot list, retrying after 4 seconds...
    failed to get snapshot list, retrying after 8 seconds...
    failed to get snapshot list, retrying after 12 seconds...
    failed to get snapshot list, retrying after 16 seconds...
Got snapshot list!
(1/2055429) 20031015074815 http://demiart.ru:80/  [Skip: already on disk]
(2/2055429) 20031016111427 http://demiart.ru:80/about.shtml  [Skip: already on disk]
(3/2055429) 20031016112139 http://demiart.ru:80/base.shtml  [Skip: already on disk]
(4/2055429) 20031016112323 http://demiart.ru:80/banners.shtml  [Skip: already on disk]
(5/2055429) 20031016112701 http://demiart.ru:80/ash.css  [Skip: already on disk]
(6/2055429) 20031016113118 http://demiart.ru:80/eva.shtml  [Skip: already on disk]
(7/2055429) 20031016113309 http://demiart.ru:80/fallen_angel.shtml  [Skip: already on disk]
(8/2055429) 20031016113809 http://demiart.ru:80/evol.shtml  [Skip: already on disk]
(9/2055429) 20031016114729 http://demiart.ru:80/guestbook.shtml  [Skip: already on disk]
(10/2055429) 20031016114735 http://demiart.ru:80/checklinks.shtml  [Skip: already on disk]
...
(143/2055429) 20040203164619 http://demiart.ru:80/karlo.jpg  [Skip: already on disk]
(144/2055429) 20040208192527 http://www.demiart.ru:80/  [Skip: already on disk]
(145/2055429) 20040214235210 http://demiart.ru:80/about.shtml  [Skip: already on disk]
(146/2055429) 20040215000439 http://demiart.ru:80/banners.shtml  [Skip: already on disk]
(147/2055429) 20040215000915 http://demiart.ru:80/checklinks.shtml  [Skip: already on disk]
(148/2055429) 20040215213504 http://demiart.ru:80/books/12923m.jpg  [Skip: already on disk]
(149/2055429) 20040215214341 http://demiart.ru:80/books/81341m.jpg  [Skip: already on disk]
(150/2055429) 20040222091135 http://demiart.ru:80/z80.shtml  [Skip: already on disk]
(151/2055429) 20040222101910 http://demiart.ru:80/forum/index.php?act=Help  [Skip: already on disk]
(152/2055429) 20040222102707 http://demiart.ru:80/forum/index.php?act=Login&amp  [Skip: already on disk]
(153/2055429) 20040222104000 http://demiart.ru:80/forum/index.php?act=Members&amp  [Skip: already on disk]
(154/2055429) 20040222105046 http://demiart.ru:80/forum/index.php?act=Reg&amp  [Skip: already on disk]
(155/2055429) 20040222105430 http://demiart.ru:80/forum/index.php?act=Search&amp  [Skip: already on disk]
(156/2055429) 20040222105609 http://demiart.ru:80/download/index.shtml  [Skip: already on disk]
(157/2055429) 20040222110235 http://demiart.ru:80/forum/index.php  [Skip: already on disk]
(158/2055429) 20040226054919 http://demiart.ru:80/  [Skip: already on disk]
(159/2055429) 20040228080952 http://demiart.ru:80/forum/index.php?c=3  [Skip: already on disk]
(160/2055429) 20040228081328 http://demiart.ru:80/forum/index.php?showforum=4  [Skip: already on disk]
(161/2055429) 20040228081427 http://demiart.ru:80/forum/index.php?act=Stats  [Skip: already on disk]
(162/2055429) 20040228081501 http://demiart.ru:80/forum/index.php?showforum=5  [Skip: already on disk]
(163/2055429) 20040228081544 http://demiart.ru:80/forum/index.php?c=5  [Skip: already on disk]
(164/2055429) 20040228081859 http://demiart.ru:80/forum/index.php?showforum=6  [Skip: already on disk]
(165/2055429) 20040228081939 http://demiart.ru:80/forum/index.php?act=calendar  [Skip: already on disk]
(166/2055429) 20040228081955 http://demiart.ru:80/forum/index.php?s=&act=chat&pop=1  [Skip: already on disk]
(167/2055429) 20040228082110 http://demiart.ru:80/forum/index.php?showforum=10  [Skip: already on disk]
(168/2055429) 20040228082113 http://demiart.ru:80/forum/index.php?act=idx  [Skip: already on disk]
(169/2055429) 20040228082123 http://demiart.ru:80/forum/index.php?showforum=7  [Skip: already on disk]
(170/2055429) 20040228145014 http://demiart.ru:80/forum/style_images/1/f_norm_no.gif  [Skip: already on disk]
(171/2055429) 20040228152823 http://demiart.ru:80/forum/style_images/1/f_poll.gif  [Skip: already on disk]
(172/2055429) 20040228155134 http://demiart.ru:80/forum/style_images/1/f_poll_no.gif  [Skip: already on disk]
(173/2055429) 20040228191947 http://demiart.ru:80/forum/style_images/1/icon1.gif  [Skip: already on disk]
(174/2055429) 20040229125101 http://demiart.ru:80/forum/style_images/1/cal_newevent.gif  [Skip: already on disk]
(175/2055429) 20040229131835 http://demiart.ru:80/forum/style_images/1/icon12.gif  [Skip: already on disk]
(176/2055429) 20040305085552 http://demiart.ru:80/forum/index.php?showtopic=133&amp  [Skip: already on disk]
(177/2055429) 20040305085728 http://demiart.ru:80/forum/index.php?showuser=27  [Skip: already on disk]
(178/2055429) 20040305085741 http://demiart.ru:80/forum/index.php?showtopic=128&amp  [Skip: already on disk]
(179/2055429) 20040305085830 http://demiart.ru:80/forum/index.php?showforum=9  [Skip: already on disk]
(180/2055429) 20040305085905 http://demiart.ru:80/forum/index.php?showtopic=90&amp  [Skip: already on disk]
(181/2055429) 20040305085921 http://demiart.ru:80/forum/index.php?showuser=1  [Skip: already on disk]
(182/2055429) 20040305085950 http://demiart.ru:80/forum/index.php?showtopic=129&amp  [Skip: already on disk]
(183/2055429) 20040305090222 http://demiart.ru:80/forum/index.php?showuser=24  [Skip: already on disk]
(184/2055429) 20040305090327 http://demiart.ru:80/forum/index.php?showtopic=89&amp  [Skip: already on disk]
(185/2055429) 20040305090333 http://demiart.ru:80/forum/index.php?showtopic=131&amp  [Skip: already on disk]
(186/2055429) 20040305090334 http://demiart.ru:80/forum/index.php?showuser=57  [Skip: already on disk]
(187/2055429) 20040305090338 http://demiart.ru:80/forum/index.php?showforum=8  [Skip: already on disk]
(188/2055429) 20040305090349 http://demiart.ru:80/forum/index.php?showtopic=121&amp  [Skip: already on disk]
(189/2055429) 20040309120046 http://demiart.ru:80/links_humor.shtml  [Skip: already on disk]
(190/2055429) 20040309120100 http://demiart.ru:80/links_films.shtml  [Skip: already on disk]
(191/2055429) 20040309120104 http://demiart.ru:80/pos/index.htm  [Skip: already on disk]
(192/2055429) 20040309120107 http://demiart.ru:80/portfolio/drr/index.htm  [Skip: already on disk]
(193/2055429) 20040309120143 http://demiart.ru:80/links_dark.shtml  [Skip: already on disk]
(194/2055429) 20040309120219 http://demiart.ru:80/links_music.shtml  [Skip: already on disk]
(195/2055429) 20040309120358 http://demiart.ru:80/links_gfx.shtml  [Skip: already on disk]
(196/2055429) 20040309120403 http://demiart.ru:80/forum/index.php?showuser=78  [Skip: already on disk]
(197/2055429) 20040309120405 http://demiart.ru:80/portfolio2.shtml  [Skip: already on disk]
(198/2055429) 20040309120409 http://demiart.ru:80/guestbook.shtml?n=50  [Skip: already on disk]
(199/2055429) 20040309120419 http://demiart.ru:80/links_zxscene.shtml  [Skip: already on disk]
(200/2055429) 20040309120423 http://demiart.ru:80/links_others.shtml  [Skip: already on disk]
```

**Comment by burner1024** [comment]
Yes, `?` should've been skipped.

**Comment by defder-su** [comment]
It works.
