### ISSUE TITLE
Launch instability

### ISSUE THREAD

**Issue by defder-su** [BGforgeNet/yawbdl#3]
On startup, the app often crashes (if not, works good thereafter):

$ ./yawbdl.py -d btdigg.org -o yawbdl_btdigg.org --no-fail --retries 10 --delay 3
Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [WinError 10061] ▒▒▒▒▒▒▒▒▒▒▒ ▒▒ ▒▒▒▒▒▒▒▒▒▒▒, ▒.▒. ▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒ ▒▒▒▒▒▒▒▒▒▒▒

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\urllib3\connectionpool.py", line 493, in _make_request
    conn.request(
    ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<6 lines>...
        enforce_content_length=enforce_content_length,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\urllib3\connection.py", line 445, in request
    self.endheaders()
    ~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1091, in _send_output
    self.send(msg)
    ~~~~~~~~~^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1035, in send
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\urllib3\connection.py", line 276, in connect
    self.sock = self._new_conn()
                ~~~~~~~~~~~~~~^^
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\urllib3\connection.py", line 213, in _new_conn
    raise NewConnectionError(
        self, f"Failed to establish a new connection: {e}"
    ) from e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000020939468C20>: Failed to establish a new connection: [WinError 10061] ▒▒▒▒▒▒▒▒▒▒▒ ▒▒ ▒▒▒▒▒▒▒▒▒▒▒, ▒.▒. ▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒ ▒▒▒▒▒▒▒▒▒▒▒

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='web.archive.org', port=80): Max retries exceeded with url: /cdx/search/cdx?output=json&url=btdigg.org&matchType=host&filter=statuscode:200&fl=timestamp,original (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020939468C20>: Failed to establish a new connection: [WinError 10061] ▒▒▒▒▒▒▒▒▒▒▒ ▒▒ ▒▒▒▒▒▒▒▒▒▒▒, ▒.▒. ▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒ ▒▒▒▒▒▒▒▒▒▒▒'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SaveSites\yawbdl.py", line 165, in <module>
    snap_list = get_snapshot_list()
  File "D:\SaveSites\yawbdl.py", line 58, in get_snapshot_list
    resp = requests.get(cdx_url + params)
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='web.archive.org', port=80): Max retries exceeded with url: /cdx/search/cdx?output=json&url=btdigg.org&matchType=host&filter=statuscode:200&fl=timestamp,original (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020939468C20>: Failed to establish a new connection: [WinError 10061] ▒▒▒▒▒▒▒▒▒▒▒ ▒▒ ▒▒▒▒▒▒▒▒▒▒▒, ▒.▒. ▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒ ▒▒▒▒▒▒▒▒▒▒▒'))

**Comment by burner1024** [comment]
```
./yawbdl.py -d btdigg.org -o yawbdl_btdigg.org --no-fail --retries 10 --delay 3
(1/23062) 20110205030240 http://btdigg.org:80/  [OK]
(2/23062) 20110226231305 http://btdigg.org:80/about.html  [OK]
(3/23062) 20110226231319 http://btdigg.org:80/top100.html  [OK]
(4/23062) 20110228192719 http://btdigg.org:80/legal.html  [OK]
(5/23062) 20110611092019 http://btdigg.org/robots.txt  [OK]
(6/23062) 20110611092020 http://btdigg.org/  [OK]
(7/23062) 20110611092020 http://btdigg.org/gray.css  [OK]
(8/23062) 20110611092021 http://btdigg.org/fb.png  [OK]
(9/23062) 20110611092021 http://btdigg.org/logo.png  [OK]
(10/23062) 20110611092021 http://btdigg.org/twitter.png  [OK]
(11/23062) 20110611092049 http://www.btdigg.org/  [OK]
(12/23062) 20110611092049 http://www.btdigg.org/robots.txt  [OK]
(13/23062) 20110611092050 http://www.btdigg.org/gray.css  [OK]
(14/23062) 20110611092051 http://www.btdigg.org/fb.png  [OK]
(15/23062) 20110611092051 http://www.btdigg.org/logo.png  [OK]
(16/23062) 20110611092051 http://www.btdigg.org/twitter.png  [OK]
(17/23062) 20110622120332 http://www.btdigg.org/robots.txt  [OK]
(18/23062) 20110622120335 http://btdigg.org/robots.txt  [OK]
(19/23062) 20110622120341 http://btdigg.org/  [OK]
(20/23062) 20110622120348 http://btdigg.org/twitter.png      failed to download, retrying after 6 seconds... 
    failed to download, retrying after 12 seconds... 
    failed to download, retrying after 18 seconds... 
    failed to download, retrying after 24 seconds... 
    failed to download, retrying after 30 seconds... 
    failed to download, retrying after 36 seconds... 
    failed to download, retrying after 42 seconds... 
[OK]
(21/23062) 20110622120414 http://www.btdigg.org/  [OK]
(22/23062) 20110622120418 http://btdigg.org/logo.png  [OK]
(23/23062) 20110622120424 http://btdigg.org/fb.png  [OK]
(24/23062) 20110622120431 http://btdigg.org/gray.css  [OK]
(25/23062) 20110622120434 http://btdigg.org/favicon.ico      failed to download, retrying after 6 seconds... 
[OK]
(26/23062) 20110630073549 http://btdigg.org:80/  [OK]
```

I think you triggered IA WAF or something. Maybe try later or from another IP.

**Comment by defder-su** [comment]
It crashes instantly, not after 30 seconds (`Max retries exceeded`, `--retries 10 --delay 3`).

**Comment by burner1024** [comment]
Yes, it died on snapshot list.
I added retries for it too.

**Comment by defder-su** [comment]
It's stable now.
